from __future__ import annotations

import json
import uuid
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from typing import Any, Iterator

from .config import (
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    ASESOR_EMAIL,
    ASESOR_PASSWORD,
    SESSION_TTL_SECONDS,
)
from .database import Database
from .security import hash_password, new_token, token_hash
from .schema import normalize_payload


SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS public.users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
        display_name TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('admin', 'asesor')),
        password_salt TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL,
        last_login_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS public.sessions (
        token_hash TEXT PRIMARY KEY,
        csrf_token TEXT NOT NULL,
        user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS public.minute_reference_counters (
        period TEXT PRIMARY KEY,
        last_value INTEGER NOT NULL CHECK (last_value > 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS public.minutes (
        id TEXT PRIMARY KEY,
        reference TEXT NOT NULL UNIQUE,
        client_name TEXT NOT NULL,
        document_number TEXT,
        status TEXT NOT NULL DEFAULT 'borrador'
            CHECK (status IN ('borrador', 'generada')),
        payload_json JSONB NOT NULL,
        created_by BIGINT NOT NULL REFERENCES public.users(id),
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL,
        generated_at TIMESTAMPTZ
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_minutes_created_by
        ON public.minutes(created_by)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_minutes_updated_at
        ON public.minutes(updated_at DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at
        ON public.sessions(expires_at)
    """,
    """
    CREATE TABLE IF NOT EXISTS public.login_attempts (
        attempt_key TEXT NOT NULL,
        attempted_at TIMESTAMPTZ NOT NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_login_attempts_key_time
        ON public.login_attempts(attempt_key, attempted_at)
    """,
    """
    CREATE TABLE IF NOT EXISTS public.audit_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES public.users(id),
        action TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT,
        created_at TIMESTAMPTZ NOT NULL,
        details_json JSONB NOT NULL DEFAULT '{}'::jsonb
    )
    """,
    "ALTER TABLE public.users ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE public.minute_reference_counters ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE public.minutes ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY",
)


def utc_datetime() -> datetime:
    return datetime.now(timezone.utc)


def _public_value(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat(timespec="seconds")
    if isinstance(value, uuid.UUID):
        return str(value)
    return value


def _public_row(row: dict[str, Any]) -> dict[str, Any]:
    return {key: _public_value(value) for key, value in row.items()}


class PostgresDatabase:
    """PostgreSQL implementation of the SQLite ``Database`` interface.

    Connections are deliberately short lived and prepared statements are disabled.
    This makes every operation safe to use through Supabase Supavisor in transaction
    pooling mode, which is the recommended connection type for serverless runtimes.
    """

    def __init__(self, database_url: str) -> None:
        if not database_url:
            raise RuntimeError(
                "DATABASE_URL o POSTGRES_URL es obligatorio para usar PostgreSQL."
            )
        self.database_url = database_url

    @contextmanager
    def connect(self) -> Iterator[Any]:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ModuleNotFoundError as error:  # pragma: no cover - deployment guard
            raise RuntimeError(
                "Falta psycopg. Instala las dependencias de requirements.txt."
            ) from error

        connection = psycopg.connect(
            self.database_url,
            connect_timeout=10,
            prepare_threshold=None,
            row_factory=dict_row,
        )
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def initialize(self) -> list[dict[str, str]]:
        if ADMIN_PASSWORD is None or ASESOR_PASSWORD is None:
            raise RuntimeError(
                "Define VH_ADMIN_PASSWORD y VH_ASESOR_PASSWORD (mínimo 16 caracteres) "
                "antes de iniciar la aplicación en producción."
            )

        with self.connect() as connection:
            # Serializa el primer arranque: CREATE TABLE IF NOT EXISTS no evita por sí
            # solo todas las carreras del catálogo entre dos cold starts simultáneos.
            connection.execute("SELECT pg_advisory_xact_lock(21948, 1)")
            for statement in SCHEMA_STATEMENTS:
                connection.execute(statement)
            self._seed_user(
                connection,
                ADMIN_EMAIL,
                "Administrador Villa Hermosa",
                "admin",
                ADMIN_PASSWORD,
            )
            self._seed_user(
                connection,
                ASESOR_EMAIL,
                "Asesor Villa Hermosa",
                "asesor",
                ASESOR_PASSWORD,
            )
            self._prune_sessions(connection)
        return []

    @staticmethod
    def _seed_user(
        connection: Any,
        email: str,
        display_name: str,
        role: str,
        password: str,
    ) -> None:
        salt, digest = hash_password(password)
        connection.execute(
            """
            INSERT INTO public.users (
                email, display_name, role, password_salt, password_hash, created_at
            ) VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (email) DO NOTHING
            """,
            (email.lower(), display_name, role, salt, digest, utc_datetime()),
        )

    @staticmethod
    def _prune_sessions(connection: Any) -> None:
        connection.execute(
            "DELETE FROM public.sessions WHERE expires_at <= CURRENT_TIMESTAMP"
        )

    def get_user_by_email(self, email: str) -> dict[str, Any] | None:
        with self.connect() as connection:
            row = connection.execute(
                "SELECT * FROM public.users WHERE email = lower(%s) AND active = TRUE",
                (email,),
            ).fetchone()
        return _public_row(row) if row else None

    def create_session(self, user_id: int) -> tuple[str, str]:
        token = new_token(36)
        csrf = new_token(24)
        now = utc_datetime()
        expires = now + timedelta(seconds=SESSION_TTL_SECONDS)
        with self.connect() as connection:
            self._prune_sessions(connection)
            connection.execute(
                """
                INSERT INTO public.sessions (
                    token_hash, csrf_token, user_id, expires_at, created_at
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                (token_hash(token), csrf, user_id, expires, now),
            )
            connection.execute(
                "UPDATE public.users SET last_login_at = %s WHERE id = %s",
                (now, user_id),
            )
        return token, csrf

    def get_session(self, token: str) -> dict[str, Any] | None:
        with self.connect() as connection:
            row = connection.execute(
                """
                SELECT s.csrf_token, s.expires_at,
                       u.id, u.email, u.display_name, u.role, u.last_login_at
                FROM public.sessions s
                JOIN public.users u ON u.id = s.user_id
                WHERE s.token_hash = %s
                  AND s.expires_at > CURRENT_TIMESTAMP
                  AND u.active = TRUE
                """,
                (token_hash(token),),
            ).fetchone()
        return _public_row(row) if row else None

    def delete_session(self, token: str) -> None:
        with self.connect() as connection:
            connection.execute(
                "DELETE FROM public.sessions WHERE token_hash = %s",
                (token_hash(token),),
            )

    def allow_login_attempt(
        self, key: str, *, window_seconds: int, max_attempts: int
    ) -> bool:
        now = utc_datetime()
        cutoff = now - timedelta(seconds=window_seconds)
        with self.connect() as connection:
            connection.execute(
                "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))", (key,)
            )
            connection.execute(
                "DELETE FROM public.login_attempts WHERE attempted_at < %s",
                (cutoff,),
            )
            row = connection.execute(
                """
                SELECT COUNT(*) AS total
                FROM public.login_attempts
                WHERE attempt_key = %s AND attempted_at >= %s
                """,
                (key, cutoff),
            ).fetchone()
            if int(row["total"] or 0) >= max_attempts:
                return False
            connection.execute(
                """
                INSERT INTO public.login_attempts (attempt_key, attempted_at)
                VALUES (%s, %s)
                """,
                (key, now),
            )
        return True

    def reset_login_attempt(self, key: str) -> None:
        with self.connect() as connection:
            connection.execute(
                "DELETE FROM public.login_attempts WHERE attempt_key = %s",
                (key,),
            )

    def list_users(self) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT id, email, display_name, role, active, created_at, last_login_at
                FROM public.users ORDER BY role, display_name
                """
            ).fetchall()
        return [_public_row(row) for row in rows]

    def count_minutes_for_user(self, user_id: int) -> int:
        with self.connect() as connection:
            row = connection.execute(
                "SELECT COUNT(*) AS total FROM public.minutes WHERE created_by = %s",
                (user_id,),
            ).fetchone()
        return int(row["total"] or 0)

    @staticmethod
    def _reference_for(connection: Any) -> str:
        period = utc_datetime().strftime("%Y%m")
        row = connection.execute(
            """
            INSERT INTO public.minute_reference_counters (period, last_value)
            VALUES (%s, 1)
            ON CONFLICT (period) DO UPDATE
            SET last_value = minute_reference_counters.last_value + 1
            RETURNING last_value
            """,
            (period,),
        ).fetchone()
        return f"VH-{period}-{int(row['last_value']):04d}"

    def create_minute(self, user_id: int, payload: dict[str, Any]) -> dict[str, Any]:
        from psycopg.types.json import Jsonb

        payload = normalize_payload(payload)
        minute_id = str(uuid.uuid4())
        now = utc_datetime()
        client_name, document_number = Database._buyer_identity(payload)
        with self.connect() as connection:
            reference = self._reference_for(connection)
            connection.execute(
                """
                INSERT INTO public.minutes (
                    id, reference, client_name, document_number, payload_json,
                    created_by, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    minute_id,
                    reference,
                    client_name,
                    document_number,
                    Jsonb(payload),
                    user_id,
                    now,
                    now,
                ),
            )
            self._audit(connection, user_id, "crear", "minuta", minute_id)
        item = self.get_minute(minute_id, user_id, "admin")
        if item is None:  # pragma: no cover - defensive consistency guard
            raise RuntimeError("No se pudo recuperar la minuta recién creada.")
        return item

    def get_minute(
        self, minute_id: str, user_id: int, role: str
    ) -> dict[str, Any] | None:
        where = "m.id = %s"
        params: list[Any] = [minute_id]
        if role != "admin":
            where += " AND m.created_by = %s"
            params.append(user_id)
        with self.connect() as connection:
            row = connection.execute(
                f"""
                SELECT m.*, u.display_name AS owner_name, u.email AS owner_email
                FROM public.minutes m JOIN public.users u ON u.id = m.created_by
                WHERE {where}
                """,
                params,
            ).fetchone()
        return self._minute_row(row) if row else None

    def list_minutes(self, user_id: int, role: str) -> list[dict[str, Any]]:
        where = "" if role == "admin" else "WHERE m.created_by = %s"
        params: tuple[Any, ...] = () if role == "admin" else (user_id,)
        with self.connect() as connection:
            rows = connection.execute(
                f"""
                SELECT m.*, u.display_name AS owner_name, u.email AS owner_email
                FROM public.minutes m JOIN public.users u ON u.id = m.created_by
                {where}
                ORDER BY m.updated_at DESC
                """,
                params,
            ).fetchall()
        return [self._minute_row(row) for row in rows]

    def update_minute(
        self,
        minute_id: str,
        user_id: int,
        role: str,
        payload: dict[str, Any],
    ) -> dict[str, Any] | None:
        from psycopg.types.json import Jsonb

        payload = normalize_payload(payload)
        existing = self.get_minute(minute_id, user_id, role)
        if not existing:
            return None
        now = utc_datetime()
        client_name, document_number = Database._buyer_identity(payload)
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE public.minutes
                SET client_name = %s, document_number = %s, payload_json = %s,
                    updated_at = %s, status = 'borrador'
                WHERE id = %s
                """,
                (
                    client_name,
                    document_number,
                    Jsonb(payload),
                    now,
                    minute_id,
                ),
            )
            self._audit(connection, user_id, "editar", "minuta", minute_id)
        return self.get_minute(minute_id, user_id, role)

    def mark_generated(self, minute_id: str, user_id: int) -> None:
        now = utc_datetime()
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE public.minutes
                SET status = 'generada', generated_at = %s, updated_at = %s
                WHERE id = %s
                """,
                (now, now, minute_id),
            )
            self._audit(connection, user_id, "generar", "minuta", minute_id)

    def delete_minute(self, minute_id: str, user_id: int) -> bool:
        with self.connect() as connection:
            cursor = connection.execute(
                "DELETE FROM public.minutes WHERE id = %s", (minute_id,)
            )
            deleted = bool(cursor.rowcount)
            if deleted:
                self._audit(connection, user_id, "eliminar", "minuta", minute_id)
        return deleted

    def stats(self, user_id: int, role: str) -> dict[str, int]:
        where = "" if role == "admin" else "WHERE created_by = %s"
        params: tuple[Any, ...] = () if role == "admin" else (user_id,)
        with self.connect() as connection:
            row = connection.execute(
                f"""
                SELECT COUNT(*) AS total,
                       SUM(CASE WHEN status = 'borrador' THEN 1 ELSE 0 END) AS borradores,
                       SUM(CASE WHEN status = 'generada' THEN 1 ELSE 0 END) AS generadas
                FROM public.minutes {where}
                """,
                params,
            ).fetchone()
        return {
            "total": int(row["total"] or 0),
            "borradores": int(row["borradores"] or 0),
            "generadas": int(row["generadas"] or 0),
        }

    @staticmethod
    def _minute_row(row: dict[str, Any]) -> dict[str, Any]:
        item = _public_row(row)
        raw_payload = item.pop("payload_json")
        if isinstance(raw_payload, str):
            raw_payload = json.loads(raw_payload)
        item["payload"] = normalize_payload(raw_payload)
        item["client_name"], item["document_number"] = Database._buyer_identity(
            item["payload"]
        )
        return item

    @staticmethod
    def _audit(
        connection: Any,
        user_id: int,
        action: str,
        entity_type: str,
        entity_id: str | None,
        details: dict[str, Any] | None = None,
    ) -> None:
        from psycopg.types.json import Jsonb

        connection.execute(
            """
            INSERT INTO public.audit_log (
                user_id, action, entity_type, entity_id, created_at, details_json
            ) VALUES (%s, %s, %s, %s, %s, %s)
            """,
            (
                user_id,
                action,
                entity_type,
                entity_id,
                utc_datetime(),
                Jsonb(details or {}),
            ),
        )
