-- Esquema privado para Villa Hermosa Minutas.
-- La aplicación se conecta mediante el pool transaccional de Supavisor.

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
    display_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'asesor')),
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.sessions (
    token_hash TEXT PRIMARY KEY,
    csrf_token TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS public.minute_reference_counters (
    period TEXT PRIMARY KEY,
    last_value INTEGER NOT NULL CHECK (last_value > 0)
);

CREATE TABLE IF NOT EXISTS public.minutes (
    id TEXT PRIMARY KEY,
    reference TEXT NOT NULL UNIQUE,
    client_name TEXT NOT NULL,
    document_number TEXT,
    status TEXT NOT NULL DEFAULT 'borrador'
        CHECK (status IN ('borrador', 'generada')),
    payload_json JSONB NOT NULL,
    created_by BIGINT NOT NULL REFERENCES public.users(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    generated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_minutes_created_by
    ON public.minutes(created_by);
CREATE INDEX IF NOT EXISTS idx_minutes_updated_at
    ON public.minutes(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at
    ON public.sessions(expires_at);

CREATE TABLE IF NOT EXISTS public.login_attempts (
    attempt_key TEXT NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_key_time
    ON public.login_attempts(attempt_key, attempted_at);

CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Ninguna tabla queda expuesta a los roles anon/authenticated de PostgREST.
-- El propietario usado por el backend conserva acceso a través de la conexión directa.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minute_reference_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
